use_frameworks!

target 'AsyncTask_Example' do
  pod 'AsyncTask', :path => '../'

  target 'AsyncTask_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
